# Generated by Django 5.1.6 on 2025-02-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the property', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the property')),
                ('property_type', models.CharField(choices=[('APARTMENT', 'AP'), ('HOUSE', 'HS'), ('COMMERCIAL ', 'CM'), ('LAND ', 'LD')], help_text='Type of the property', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in your currency', max_digits=12)),
                ('size', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=10)),
                ('address', models.CharField(help_text='Property address', max_length=255)),
                ('city', models.CharField(help_text='City where the property is located', max_length=100)),
                ('state', models.CharField(help_text='State or region of the property', max_length=100)),
                ('zip_code', models.CharField(help_text='Postal/Zip code', max_length=10)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Main image of the property', null=True, upload_to='property_images/')),
            ],
        ),
    ]
